server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Konfigurasi ini sangat penting agar React Router (Single Page Application)
        # tidak error 404 ketika user me-refresh halaman selain halaman utama (/).
        try_files $uri $uri/ /index.html;
    }

    # Optimasi cache untuk asset statis
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
